spring.application.name=app

# DATABASE
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=0

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# ===============================
# MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# JWT SECRET KEY
# ===============================
jwt.secret-key=${JWT_SECRET}

storage.spendoo.key=${STORAGE_SPENDOO_KEY}
storage.spendoo.secret=${STORAGE_SPENDOO_SECRET}
storage.spendoo.endpoint=${STORAGE_SPENDOO_ENDPOINT}
storage.spendoo.cdn-endpoint=${STORAGE_SPENDOO_CDN_ENDPOINT}
storage.spendoo.bucket=${STORAGE_SPENDOO_BUCKET}

identity.resources.profile-image-directory=${PROFILE_IMAGE_DIRECTORY}

# Multipart file size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file-size.modules.identity=5

server.forward-headers-strategy=framework

internal.api.base-url=${INTERNAL_API_BASE_URL:http://localhost:8080}
ai.service.base-url=${AI_SERVICE_BASE_URL:http://127.0.0.1:8000}