package org.spendoo.savingGoals.entity

enum class AchievementCode {
    SAVINGS_L1,
    SAVINGS_L2,
    SAVINGS_L3,
    SAVINGS_L4,
    HIGH_FIVE,
    DOUBLE_FIVE,
    THE_FINISHER,
    PRIORITY_SAVER,
    LOGIN_STREAK_L1,
    LOGIN_STREAK_L2,
    LOGIN_STREAK_L3,
    LOGIN_STREAK_L4,
    TRANSACTION_STREAK_L1,
    TRANSACTION_STREAK_L2,
    TRANSACTION_STREAK_L3,
    TRANSACTION_STREAK_L4,
    CATEGORY_L1,
    CATEGORY_L2,
    CATEGORY_L3,
    CATEGORY_L4
}
