name: Deploy Spring Boot

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Firebase Credentials
        run: |
          mkdir -p app/src/main/resources
          echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 -d > app/src/main/resources/spendoo-firebase-adminsdk.json

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t josephsameh/spendoo-backend:latest .
          docker push josephsameh/spendoo-backend:latest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sync App Settings to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --settings \
                DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
                DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
                JWT_SECRET="${{ secrets.JWT_SECRET }}" \
                MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
                MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
                PROFILE_IMAGE_DIRECTORY="${{ secrets.PROFILE_IMAGE_DIRECTORY }}" \
                STORAGE_SPENDOO_BUCKET="${{ secrets.STORAGE_SPENDOO_BUCKET }}" \
                STORAGE_SPENDOO_CDN_ENDPOINT="${{ secrets.STORAGE_SPENDOO_CDN_ENDPOINT }}" \
                STORAGE_SPENDOO_ENDPOINT="${{ secrets.STORAGE_SPENDOO_ENDPOINT }}" \
                STORAGE_SPENDOO_KEY="${{ secrets.STORAGE_SPENDOO_KEY }}" \
                STORAGE_SPENDOO_SECRET="${{ secrets.STORAGE_SPENDOO_SECRET }}" \
                INTERNAL_API_BASE_URL="${{ secrets.INTERNAL_API_BASE_URL }}" \
                AI_SERVICE_BASE_URL="${{ secrets.AI_SERVICE_BASE_URL }}" \
                SPENDOO_HMAC_SECRET_KEY="${{ secrets.SPENDOO_HMAC_SECRET_KEY }}"

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'josephsameh/spendoo-backend:latest'