name: Deploy Spring Boot

on:
#  push:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t josephsameh/spendoo-backend:latest .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push josephsameh/spendoo-backend:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull josephsameh/spendoo-backend:latest
            docker stop springboot-container || true
            docker rm springboot-container || true
            docker run -d --restart=always --name springboot-container -p 8080:8080 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
            -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
            -e PROFILE_IMAGE_DIRECTORY=${{ secrets.PROFILE_IMAGE_DIRECTORY }} \
            -e STORAGE_SPENDOO_BUCKET=${{ secrets.STORAGE_SPENDOO_BUCKET }} \
            -e STORAGE_SPENDOO_CDN_ENDPOINT=${{ secrets.STORAGE_SPENDOO_CDN_ENDPOINT }} \
            -e STORAGE_SPENDOO_ENDPOINT=${{ secrets.STORAGE_SPENDOO_ENDPOINT }} \
            -e STORAGE_SPENDOO_KEY=${{ secrets.STORAGE_SPENDOO_KEY }} \
            -e STORAGE_SPENDOO_SECRET=${{ secrets.STORAGE_SPENDOO_SECRET }} \
              josephsameh/spendoo-backend:latest